pipeline {
	agent any
	parameters {
		booleanParam(name: 'status', defaultValue: false, description: 'Execution status')
		string(name: 'environment', defaultValue: "develop", description: 'Deploy on environment')
		text(name: 'description', defaultValue: "This is Spring Boot Application. \nDefine how to deploy app on jenkins.", description: 'Jenkins Demo')
	}
	stages {
		stage ("Resource Cleanup") {
			steps {
				deleteDir()
				echo "Application status: ${params.status}"
				echo "Application deploy on environment: ${params.environment}"
				echo "Application discription: ${params.description}"
			}
		}
		stage ("Clone") {
			steps {
				dir("Jenkins-demo-service") {
					git url:"https://github.com/Dhwanil-Patel/Jenkins-demo.git", branch:"develop"
				}
			}
		}
		stage ("Build") {
			steps {
				dir("Jenkins-demo-service") {
					sh "mvn clean install"
				}
			}
		}
		stage ("Test") {
			steps {
				dir("Jenkins-demo-service") {
					sh "mvn test"
				}
			}
		}
		stage ("Complete") {
			steps {
				echo "Job execution completed!!!"
			}
		}
	}
}