pipeline {
	agent any
	parameters {
		booleanParam(name: 'status', defaultValue: false, description: 'Execution status')
		string(name: 'author', defaultValue: "Dhwanil", description: 'Person who deploy')
		text(name: 'description', defaultValue: "This is Spring Boot Application. \nDefine how to deploy app on jenkins.", description: 'Jenkins Demo')
		choice(name: 'environment', choices: ['development', 'test', 'stage'], description: 'Environment you willing to deploy')
	}
	stages {
		stage ("Resource Cleanup") {
			steps {
				deleteDir()
				echo "Application status: ${params.status}"
				echo "Application deploy by: ${params.author}"
				echo "Application discription: ${params.description}"
				echo "Application deploy on environment: ${params.environment}"
			}
		}
		stage ("Clone") {
			steps {
				dir("Jenkins-demo-service") {
					git url:"https://github.com/Dhwanil-Patel/Jenkins-demo.git", branch:"develop"
				}
			}
		}
		stage ("Build") {
			steps {
				dir("Jenkins-demo-service") {
					sh "mvn clean install"
				}
			}
		}
		stage ("Test") {
			steps {
				dir("Jenkins-demo-service") {
					sh "mvn test"
				}
			}
		}
		stage ("Complete") {
			steps {
				echo "Job execution completed!!!"
			}
		}
	}
}